# Generated by Django 2.2.6 on 2019-10-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
