export const FETCH_RECORDS_READY = 'FETCH_RECORDS_READY';
export const FETCH_RECORDS_FAIL = 'FETCH_RECORDS_FAIL';
export const REFRESH_RECORD_READY = 'REFRESH_RECORD_READY';
export const REFRESH_RECORD_FAIL = 'REFRESH_RECORD_FAIL';
