export const API_ERROR = 'API_ERROR';
export const CREATE_RECORD_READY = 'CREATE_RECORD_READY';
export const REFRESH_RECORD_READY = 'REFRESH_RECORD_READY';
export const FETCH_RECORDS_READY = 'FETCH_RECORDS_READY';
export const DELETE_RECORD_READY = 'DELETE_RECORD_READY';
