export const API_ERROR = 'API_ERROR';
export const FETCH_PROJECTS_READY = 'FETCH_PROJECTS_READY';
export const REFRESH_PROJECT_READY = 'REFRESH_PROJECT_READY';
export const DELETE_PROJECT_READY = 'DELETE_PROJECT_READY';
