export const FETCH_PROJECTS_READY = 'FETCH_PROJECTS_READY';
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';
export const REFRESH_PROJECT_READY = 'REFRESH_PROJECT_READY';
export const REFRESH_PROJECT_FAIL = 'REFRESH_PROJECT_FAIL';
